Fix gh action

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,7 +13,7 @@ permissions:
   contents: write
 
 jobs:
-  bump-version:
+  check-and-release:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -22,46 +22,70 @@ jobs:
             ref: ${{ github.ref_name }}
             # path: ${{ github.ref_name }}
 
-      - name: Read and Bump Version
-        id: bump
+      - name: Read Version And Check
+        id: read_version
         run: |
           # Read the current version from the VERSION file
-          echo "started"
-          git status
-          echo "${{ github.ref_name }}"
-          pwd
-          ls -la
           version=$(cat VERSION)
-          echo "version: $version"
-
-
-          # Extract major, minor, and patch
-          major=$(echo $version | cut -d '.' -f 1 | sed 's/v//')
-          minor=$(echo $version | cut -d '.' -f 2)
-          patch=$(echo $version | cut -d '.' -f 3)
-
-          # Logic for bumping version
-          if [[ "$patch" == "x" ]]; then
-            patch=0
-          else
-            patch=$((patch + 1))
+          echo "Version from file: $version"
+    
+          # Export the version as an environment variable
+          echo "NEW_VERSION=$version" >> $GITHUB_ENV
+    
+          # Check if the tag already exists in Git
+          if git rev-parse "$NEW_VERSION" >/dev/null 2>&1; then
+            echo "Error: Tag $NEW_VERSION already exists."
+            exit 1
           fi
-          
-          # Format new version as v<major>.<minor>.<patch>
-          new_version="v${major}.${minor}.${patch}"
-          
-          # Write the new version to the VERSION file and commit
-          echo $new_version > VERSION
-          echo "version: $new_version"
-          git config --local user.name "github-actions"
-          git config --local user.email "actions@github.com"
-          git commit -am "Bump version to $new_version"
-
-          # Create a new git tag
-          git push origin ${{ github.ref_name }}
-          git tag $new_version
-          git push origin $new_version
+    
+      - name: Create Git Tag
+        if: steps.check_tag.outcome == 'success'
+        run: |
+          # Tag the commit with the version and push the tag
+          git tag $NEW_VERSION
+          git push origin $NEW_VERSION
           echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
+
+      # - name: Read and Bump Version
+      #   id: bump
+      #   run: |
+      #     # Read the current version from the VERSION file
+      #     echo "started"
+      #     git status
+      #     echo "${{ github.ref_name }}"
+      #     pwd
+      #     ls -la
+      #     version=$(cat VERSION)
+      #     echo "version: $version"
+
+
+      #     # Extract major, minor, and patch
+      #     major=$(echo $version | cut -d '.' -f 1 | sed 's/v//')
+      #     minor=$(echo $version | cut -d '.' -f 2)
+      #     patch=$(echo $version | cut -d '.' -f 3)
+
+      #     # Logic for bumping version
+      #     if [[ "$patch" == "x" ]]; then
+      #       patch=0
+      #     else
+      #       patch=$((patch + 1))
+      #     fi
+          
+      #     # Format new version as v<major>.<minor>.<patch>
+      #     new_version="v${major}.${minor}.${patch}"
+          
+      #     # Write the new version to the VERSION file and commit
+      #     echo $new_version > VERSION
+      #     echo "version: $new_version"
+      #     git config --local user.name "github-actions"
+      #     git config --local user.email "actions@github.com"
+      #     git commit -am "Bump version to $new_version"
+
+      #     # Create a new git tag
+      #     git push origin ${{ github.ref_name }}
+      #     git tag $new_version
+      #     git push origin $new_version
+      #     echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
 
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v2
